# Generated by Django 4.1.3 on 2022-11-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyto1', '0003_videogames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto1/fotos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='series',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proyecto1/videos', verbose_name='Media'),
        ),
    ]
