# Generated by Django 4.1.3 on 2022-11-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyto1', '0004_alter_series_imagen_alter_series_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto2/fotos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proyecto2/videos', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto3/fotos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proyecto3/videos', verbose_name='Media'),
        ),
    ]
